### ISSUE TITLE
Create a My Profile page

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#12]
- As a logged in user, I can access the My Profile page.
- This eventually can have a 'change password' functionality inside, but for now can just "My Profile"
- Page should be accessed by clicking the My Profile button in the existing user menu (upper-right in header).
- Create route in `App.tsx` and a page component in `src/pages`

**Comment by jaskarankukreja** [comment]
You can assign this ticket to me....

**Comment by jaskarankukreja** [comment]
would you like me to create a api for getting basic info for the user on my profile page?

**Comment by trybick** [comment]
@Jaskaran121 assigned! For an API, I'm not sure if we need it now, since there's not much info to get. We might need one later to get more user info. That could be a separate PR for later if you want.

**Comment by jaskarankukreja** [comment]
@trybick ok sure that makes sense..
