### ISSUE TITLE
Create Forgot Password functionality on Login modal

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#13]
- Look into best practices for resetting password
- Clicking forgot password on Login modal should have a way to reset it
- Will need to be created on backend and frontend

**Comment by su-per-man** [comment]
Can you please assign it to me?

**Comment by trybick** [comment]
@suman98kumar  Assigned to you. This will need to be created on the backend and frontend so let me know if you change your mind. Also do you have an email you can share? I will send the backend ENV keys.

**Comment by su-per-man** [comment]
Sure. Here is my email
suman98kumar@gmail.com
