### ISSUE TITLE
Improve UI of My Shows page

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#20]
- Improve UI/UX, styling, sizes of text and elements

**Comment by KRMeserve** [comment]
What were you thinking as far as styling changes on this page? Are there certain design styles you are trying to adhere?

It might be nice to talk about how you want this page to look so I can have a better idea of what to work on with this ticket.

**Comment by trybick** [comment]
Here are some ideas:

- I think on the My Shows page we want to focus on the bottom section, where all shows are shown
- Maybe change the heading "Following" to "All Shows"
- May want to decrease the overall size of each followed show card (`AllFollowedShows.tsx`) to get a better balance between headings and the content. Right now each card might be too big. However if we decrease the size of each card, then the content inside might overflow. To help this, let's remove the badge that says "New Episodes", "Returning", or "Ended" for now. In the future we can split the All Shows section into three sub-sections, one for each type.
- Once the badge is removed, we might want to adjust the spacing between the elements left inside the card (maybe some additional space between the network badge and the number of season)

**Comment by trybick** [comment]
Another one:

- Increase headings ("Upcoming", "Recent", "Following") font size from 1.25 rem to ~ 1.75 rem. Maybe bump up the margin bottom on the headings a few points too.

**Comment by KRMeserve** [comment]
Thanks, that should give me enough direction. We can always change things up once I get a PR up!

**Comment by trybick** [comment]
Sounds good! 😎
