### ISSUE TITLE
Add Call to Action on homepage

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#25]
Currently the home page is just a search bar. Add an image and text to the home page to give a sense of what the site is, but  would be nice to keep the search bar the main focus.

![Screen Shot 2020-09-27 at 9 48 34 AM](https://user-images.githubusercontent.com/39889198/94366485-a5226d00-00a6-11eb-9329-d85fea012008.png)

**Comment by alisherk** [comment]
I can take this one if no one is working on it

**Comment by trybick** [comment]
Sure, @alisherk it's yours

**Comment by alisherk** [comment]
should there be just a nice heading here ? Having the same logo here may be repetitive unless you have a different image

**Comment by trybick** [comment]
> should there be just a nice heading here ? Having the same logo here may be repetitive unless you have a different image

I agree the same logo could be repetitive. I am not sure to be honest. Was thinking to have a different image here, that still catches your attention, but the main focus is still the search bar.

**Comment by alisherk** [comment]
I think a stat component from Chakra would be nice here. It is a  box with a slight shadow where we can capture some kind of call to action

**Comment by trybick** [comment]
That sounds like it could work 👍
