### ISSUE TITLE
Fix center alignment of header nav links

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#29]
The navlinks ("Home", "Calendar", "My Shows" should be centered above the search bar (between the two blue lines drawn). right now they are being pushed over by the logo title on the left.

![Screen Shot 2020-09-27 at 10 06 07 AM](https://user-images.githubusercontent.com/39889198/94366929-3abefc00-00a9-11eb-9e0d-83418e5afeae.png)

**Comment by lolyparty** [comment]
Hello @trybick, I'd like to try my hands on this

**Comment by trybick** [comment]
@lolyparty Sure. Do you have an email I can send the secrets for the env files to? (I'm still looking for a better way to share env files if you can think of one)

**Comment by lolyparty** [comment]
> @lolyparty Sure. Do you have an email I can send the secrets for the env files to? (I'm still looking for a better way to share env files if you can think of one)

Yes, you can send it to webmechaservices@gmail.com

**Comment by lolyparty** [comment]
Do I need to build the backend to fix this issue?

**Comment by trybick** [comment]
Sent, thanks.

> Do I need to build the backend to fix this issue?

It's important to test centering the links when logged in and when logged out, since the Login buttons will appear if you're not logged in. You can either run the API server using the ENV files I sent or fake being logged in by changing `isLoggedin ?` to `false ?` on this line: https://github.com/trybick/tv-minder/blob/master/front/src/components/header/Header.tsx#L149

**Comment by lolyparty** [comment]
Ok, I asked because I don't write backend code. So I'll have to setup Docker right?

**Comment by trybick** [comment]
@lolyparty You don't have to start docker 👍 . The front end will still run without starting the back end, and you can work on the header. Keep in mind what I mentioned above about mocking isLoggedIn.

**Comment by trybick** [comment]
@lolyparty Another update :) I changed the API to be set to the deployed API for the local dev front end server. So don't worry about mocking anything. Starting the front end should be all you need.

**Comment by trybick** [comment]
Closing this issue because PR #38 makes the buttons left-aligned on the page.
