### ISSUE TITLE
Add dark mode to site

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#30]
This project uses chakra ui which has docs on adding dark mode here
[https://chakra-ui.com/color-mode](https://chakra-ui.com/color-mode)

Goal: Add dark mode to the site with a button in the header to toggle. The button can just be a plain button for now and would be added to Header.tsx. There already is a theme.js where the dark mode colors can start.

**Comment by luisFilipePT** [comment]
@trybick opened a PR ☝️  for this issue, hope you don't mind 😊 . Feel free to request changes!

I don't mind going through some more open issues, can I just open a PR when there is no assignee, or do I need to request to be assigned and only then open the PR? 😄 

Thanks
