### ISSUE TITLE
Style the app as you see fit 

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#35]
## Multiple people can work on this. You don't need to ask to be assigned to it :) 

_TV Minder is full-stack tv tracking web app. You can start the front end with one command (see readme)._ 

Add styling touches to the UI. 
Some ideas:
- How the items in the header are styled
- Decrease size of footer
- Add more styling to the SearchResults (see picture below)
- Style the My Shows page elements (@KRMeserve is working on this, but having multiple PRs won't hurt)

![Screen Shot 2020-10-02 at 4 22 45 PM](https://user-images.githubusercontent.com/39889198/94966623-96372280-04cb-11eb-8cc6-704cf8eb5dee.png)

**Comment by geraldobraz** [comment]
Hi 👋🏻 , I would like to try.
