### ISSUE TITLE
Add throttle to search field input

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#36]
_TV Minder is full-stack tv tracking web app. You can start the front end with one command (see readme)._

Here is the SearchInput component:
https://github.com/trybick/tv-minder/blob/master/front/src/components/search/subcomponents/SearchInput.tsx

Here is where the onChange function for SearchInput lives:
https://github.com/trybick/tv-minder/blob/master/front/src/pages/SearchPage.tsx#L33

We would like to throttle when the search is fired. If you type in the field now, notice how it flashes as searches complete for every keystroke. The idea is if you type multiple letters in a row very fast, it won't do a search for each one. It will wait maybe 300ms after you stop typing to start the search. Add a throttle so the search only starts after a delay.

**Comment by g-ravity** [comment]
I would like to take this up. I can add debouncing to the search input to achieve the desired result.

**Comment by trybick** [comment]
Sorry @g-ravity this has already been done :(
