### ISSUE TITLE
Add more welcome text in the Search Field

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#37]
### Accepting multiple PRs for this. Feel free to open PR.

_TV Minder is full-stack tv tracking web app. You can start the front end with one command (see readme)._

See picture below for the text "Welcome, search for a show". This is the first thing the user sees on the homepage, so we want to update this to include more helpful text, maybe an image, to welcome the user and give an idea how to use the site and just make the site look better :)

![Screen Shot 2020-10-02 at 4 37 44 PM](https://user-images.githubusercontent.com/39889198/94967744-aea83c80-04cd-11eb-84fd-3272bfadf6e9.png)

**Comment by rahulsawlani22** [comment]
I can make it look very catchy. Assign me

**Comment by trybick** [comment]
@Javier1019 Hey just checking in - are you still working on this?

**Comment by Javier1019** [comment]
I'm more focused the shows page, but I'm thinking of working this after the individual shows page.

**Comment by trybick** [comment]
Oops I pinged the wrong person, sorry Javier. 

@rahulsawlani22 let us know if you've worked on this, otherwise @Javier1019 may pick this up later

**Comment by rahulsawlani22** [comment]
No, I am not working on this anymore.
Thanks

**Comment by Javier1019** [comment]
@trybick could you assign this to me too? I'm pretty close to finishing the other issue.

**Comment by trybick** [comment]
@Javier1019 Sure 👍

**Comment by trybick** [comment]
@Javier1019 Also be sure to pull latest master because this area has changed since the screenshot above. If you want you can add styling or add more stuff.

**Comment by trybick** [comment]
Welcome text has been replaced by a re-worked welcome component
