### ISSUE TITLE
Update and move Contributing document

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#40]
1. Update Contibuting.md to include a bullet point about "Target the `master` branch for new pull requests.".

2. Move the contents of Contributing.md into the Readme itself, so that the text just lives inside Readme now under the Contributing section.

**Comment by omnone** [comment]
Hey i would like to do it. Thanks

**Comment by LuizHAP** [comment]
Please, don't forgot to change the topic (https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by trybick** [comment]
Thanks @LuizHAP for the PR and for the hacktoberfest update. That is good to know (topic added to this repo).
