### ISSUE TITLE
Update readme - move all Contributing text to document 

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#43]
- In the Readmne, under Contributing, delete the text that is there now, and add a link to the Controibuting file, like the following:  See [Contribution guidelines](./CONTRIBUTING.md) 

- Update the `Contributing.md` file with the the following text

**Text to update:**
Thanks for your interest! Please keep the following in mind:

Please reference our GitHub Issues page
Fork the repo and create your branch from the `master` branch
Target the `master` branch for new pull requests
Post comments on your PR for tricky areas to help reviewers understand the changes
On your pull request, ensure the Netlify build succeeds (it will be posted as PR comment)

**Comment by ShreyaPrabhu** [comment]
@trybick Can you assign this to me? I would like to work on it.
