### ISSUE TITLE
Change all uses of 'padding' to shorthand property

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#52]
Search the repo and change all 'padding' props to 'p' (this is shorthand which works in chakra ui). paddingLeft can become 'pl' and paddingBottom can be 'pb'.

**Comment by clovis1122** [comment]
@trybick can I tackle this one?

**Comment by ahthserhsluk** [comment]
i would like to help in this task:)
pls assign me to this issue to me. I will help
thank you:)
