### ISSUE TITLE
Add more styling to the Call to Action box

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#57]
Add styling as you see fit to the box in picture. Will accept multiple PRs. You don't need to ask to be assigned it :) 

The relevant file is SearchContainer.tsx

![Screen Shot 2020-10-06 at 7 19 54 PM](https://user-images.githubusercontent.com/39889198/95270198-082fa480-0809-11eb-87f9-a2d86fefd8f8.png)

**Comment by alisherk** [comment]
@trybick  Have u thought of adding tests to the project ?

**Comment by trybick** [comment]
@alisherk I'm not sure if it's a priority since there's so much still changing. Were you interested in creating tests/ do you think it would be a good idea?

**Comment by alisherk** [comment]
Yes I will be interested in adding tests incrementally.I like the code base. It is shaping nicely.

**Comment by trybick** [comment]
Ok thank you - I will make a new issue and assign it to you :)

**Comment by trybick** [comment]
@alisherk I made a new issue #63 - can you make a comment in there - then I will assign to you
