### ISSUE TITLE
Fix alignment of footer link

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#58]
See screenshot below to notice how the GitHub link is vertically higher than the other two links in the footer. This issue is to fix to the alignment so all links are in one line. See Footer.tsx file

![Screen Shot 2020-10-06 at 7 27 07 PM](https://user-images.githubusercontent.com/39889198/95270676-09150600-080a-11eb-900f-a1ccfb210a85.png)

**Comment by davidholyko** [comment]
i got this 👍
