### ISSUE TITLE
Add 0auth

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#6]
Add the ability to login with Google account, possibly GitHub, facebook etc.

**Comment by omnone** [comment]
Hey I would like to do it , can you assign this to me?

**Comment by trybick** [comment]
@omnone Assigned to you. This could be a big ticket, let me know if you're not comfortable. Also do you have an email you can share? I can send you the ENV keys for the backend.

**Comment by trybick** [comment]
@luisFilipePT if you were still interested in this, it's available

**Comment by amritanshusikdar** [comment]
Hey, Can I work on this?

**Comment by trybick** [comment]
@amritanshusikdar Sure. Are you familiar with Auth0?

**Comment by amritanshusikdar** [comment]
I have experience in backend, including authentication, so I can surely give it a try.

**Comment by trybick** [comment]
Ok sounds good 👍 I haven't used it before either, but let me know if any questions come up

do you have an email you can share here? I can email you the ENV keys.

**Comment by amritanshusikdar** [comment]
Here you go 😄 
amritanshu.sikdar@gmail.com

**Comment by trybick** [comment]
- Updating title to 0auth
- Adding the ability to login with Google is good to start (a button can be added to the Login modal)

**Comment by amritanshusikdar** [comment]
Hey I've made the PR with the Google OAuth login feature. Do check and let me know if modifications are required.
