### ISSUE TITLE
Add dark mode logo (or just the TV part)

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#61]
For the call to action on the homepage, while dark mode is, the TV image doesn't look great. We can fix this by adding a dark mode logo, or at least a dark mode version of the TV image.

![Screen Shot 2020-10-06 at 7 15 29 PM](https://user-images.githubusercontent.com/39889198/95333414-c17a9280-087a-11eb-9017-4fb67f2f84fe.png)

**Comment by GaganSingh5** [comment]
Is this issue resolved?? @trybick

**Comment by trybick** [comment]
@GaganSingh5 Someone already has this one, but there a couple other issues open if you are interested

**Comment by trybick** [comment]
@veiko We might not need this actually :)  - the section in the screenshot is probably being replaced by a 'popular shows' section. 

If you still want to add a dark mode logo to the header that would work, altho the current logo looks pretty good with dark mode enabled anyway. So no worries either way!
