### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#63]
Add tests to codebase - inspired by @alisherk - who will be heading it

**Comment by trybick** [comment]
@alisherk What framework are you thinking for tests? I usually prefer jest if we can do that. Also what do you think are the areas that would be most useful to have tests for?

**Comment by alisherk** [comment]
I think Jest and React Testing Library would be nice for React. On the backend, maybe Mocha. But I will start with the front end. We can maybe start testing utility functions and then look at the react component that are stable and write some basic assertions against those.

**Comment by trybick** [comment]
Great, sounds good. thanks! We can spit up the sections into multiple PRs.

For frontend, jest/react testing library sounds good 
For backend, it looks like jest and supertest are most popular so I would go with those

**Comment by alisherk** [comment]
I will move on to testing redux store next.

**Comment by trybick** [comment]
Awesome @alisherk 👏

**Comment by trybick** [comment]
@alisherk Closing this issue, but definitely feel free to write more tests if you're interested :)
