### ISSUE TITLE
Move position of buttons while on mobile

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#69]
While logged in, move the **dark mode button** and **Logout button** to the right side of the screen while on small screens. While the header is in large screen mode, the position shouldn't change.

**Relevant file:** 
https://github.com/trybick/tv-minder/blob/master/front/src/components/header/Header.tsx#L167

**Current picture:**
![Screen Shot 2020-10-10 at 5 24 47 PM](https://user-images.githubusercontent.com/39889198/95665394-c743d280-0b1d-11eb-981c-a9fa0f2e0283.png)

**Comment by Gabriel-nps** [comment]
I would like to contribute to this issue.

**Comment by trybick** [comment]
Great! Assigned. @GabrielFalcom

**Comment by Gabriel-nps** [comment]
Isn't there a style sheet? =P
