### ISSUE TITLE
Add 'Change password' UI to Settings page

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#81]
Add front-end functionality to change password to the Settings page. This should include three inputs (current password, new password, confirm new password) and a button to submit. It doesn't need to make any API calls or do anything else yet.

Relevant file: https://github.com/trybick/tv-minder/blob/master/front/src/pages/SettingsPage.tsx

Current settings page below. To get here, sign up and login, then click the Profile icon and Settings. 
![Screen Shot 2020-10-16 at 1 57 59 PM](https://user-images.githubusercontent.com/39889198/96292771-b7ae0900-0fb7-11eb-8183-63e328ba5176.png)

**Comment by SirPedr** [comment]
I'd like to give it a try on this one =)
