### ISSUE TITLE
Add better error handling to React front end

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#82]
Use something like Error Boundary in React to add better error handling to the front end application. See search results below for `handleErrors`, which currently just console logs the error, and see how it can be replaced in a few places with a better system.

https://github.com/trybick/tv-minder/search?q=handleErrors

**Comment by zeaus** [comment]
Hi @trybick,

I would like to give this a try.

**Comment by trybick** [comment]
@zeaus assigned 👍
