### ISSUE TITLE
Hook up change password UI to API routes

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#86]
The change password UI was just added here:
https://github.com/trybick/tv-minder/blob/master/front/src/components/changePassword/ChangePassword.tsx

In this ticket we should add an onClick to the submit button to call the `changepassword` route which was added here
https://github.com/trybick/tv-minder/commit/3506092da87a259cbfba5a81e61359a424ddb37e

We will need to send oldPassword and newPassword to the API. For example of sending data to the API, see here
https://github.com/trybick/tv-minder/blob/master/front/src/components/header/subcomponents/LoginModal.tsx#L163

**Comment by maw1a** [comment]
I can work on this. Can you assign this issue to me?

**Comment by trybick** [comment]
@maw1a assigned 👍

**Comment by maw1a** [comment]
user controller needs updating. Here is the issue I'm facing. brypt.compare is being used to compare 2 non-hashed strings.
https://github.com/trybick/tv-minder/blob/da4ef6c53265dedb154c0e874c6725c074c51858/api/src/entities/controllers/user.ts#L175

**Comment by trybick** [comment]
@maw1a Thanks for pointing that out - I have updated the controller. It works locally when sending email, oldPassword, and newPassword to it. The updates should be on the deployed API in 10-15 mins.

Here is the update if it helps:
https://github.com/trybick/tv-minder/blob/master/api/src/entities/controllers/user.ts#L174
