### ISSUE TITLE
Style the Forgot Password button

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#87]
On the Login modal (see picture), make the Forgot Password button appear closer to the site's theme. May require re-positioning the button to a more natural position and changing color, element type, and various style properties. Consider adding an icon as well (search react-icons in the project to see how to import an icon from [react-icons](https://react-icons.github.io/react-icons/)).

<img width="867" alt="Screen Shot 2020-10-16 at 7 38 59 PM" src="https://user-images.githubusercontent.com/39889198/96322544-7afa0600-0fe7-11eb-9b17-8711d48e0e90.png">

**Comment by ChristineJ82** [comment]
Hello @trybick I can work on this. Can you assign me to this issue? Thanks!

**Comment by trybick** [comment]
@ChristineJ82 assigned 👍

**Comment by ChristineJ82** [comment]
@trybick here's my pull request: https://github.com/trybick/tv-minder/pull/88
