### ISSUE TITLE
Create a page for individual shows

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#9]
User story:
- After searching for a show and seeing the results, I can click on a search result to open a new page with more info on that TV show

**Note: Something very similar will be done on the calendar page**

- On the calendar page, I can click an episode on the calendar to open a new page with more info on that episode.

**Comment by Javier1019** [comment]
Hey could I get this assigned? Do you have a design i could use for reference?

**Comment by trybick** [comment]
Hi @Javier1019 . I don't have a specific design for reference, however these two sites show the basic idea we are looking for:

https://www.themoviedb.org/tv/1434-family-guy
https://next-episode.net/brooklyn-nine-nine

^ That's the basic info we would like to display. 

So once we click a search result, we should see something like that.

Let me know if you have any questions :) I think a tricky part might be accessing the search data from the new individual show page since currently it's in local state in SearchPage.

**Comment by Javier1019** [comment]
That's alright I'll make sure to sit down and try to match the search page design. Should I make or use a separate brach or just go straight to master after I'm done?

**Comment by trybick** [comment]
Sounds good. Straight to master is good - that's where I netlify previews set up so we can preview the live changes.

**Comment by trybick** [comment]
@Javier1019 Hey just checking in - are you still working on this?

**Comment by Javier1019** [comment]
Yes, I'm still working.

**Comment by trybick** [comment]
Thanks :)

**Comment by trybick** [comment]
@Javier1019 Hey do you have an estimate when a PR might be up?
