### ISSUE TITLE
Adding more tests

### ISSUE THREAD

**Issue by trybick** [trybick/tv-minder#94]
@alisherk please write here to confirm what tests we should write next! I was thinking testing the UI components.

**Comment by alisherk** [comment]
@trybick I just finished the tv reducer tests that I would like to push. I can move to testing UI comps next.

**Comment by trybick** [comment]
@alisherk I realized this action `setCalendarEpisodesAction` is not used anywhere. Do you mind including removing this in your next PR?
https://github.com/trybick/tv-minder/blob/master/front/src/store/tv/actions.ts#L31

The related test for it can be removed too
https://github.com/trybick/tv-minder/blob/master/front/src/store/tv/__tests__/actions.test.ts#L34

**Comment by alisherk** [comment]
@trybick sure thing. My next PR will be in Jan most likely. I suppose the case in the reducer has to be removed also?

**Comment by trybick** [comment]
Sounds good, thanks for the help. I believe the reducer can stay because that action type is still being used, just by a different action.

**Comment by trybick** [comment]
@alisherk Haven't heard from you so I'm closing this, but feel free to open another issue anytime.
